# Generated by Django 4.0.4 on 2024-01-09 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=150, null=True)),
                ('post_user', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
